baseURL = "https://iorgos.net/"
languageCode = "en-us"
title = "iorgos.net"
theme = "smol"

# Parameters
[params]
    subtitle = "homepage of dragoș iorgulescu"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "sounds"
        name = "Sounds"
        url = "/sounds"
        weight = 3 
  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "E-mail"
        url = "mailto:dragos@iorgos.net"
        weight = 1   
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/diorgulescu"
        weight = 2 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://mstdn.social/web/@scentient_pencils"
        weight = 3 

    [[menu.footer]]
        name = "Proudly hosted on namebox.ro"
        url = "https://my.namebox.ro/aff.php?aff=505"
        weight = 4 

